# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LbP2cKs3lL6y8Z8Bq_GTE6o8hVnMG-CV
"""

import requests
import pandas as pd

# poe2.ninja API에서 아이템 데이터 가져오기
url = "https://poe.ninja/api/data/itemoverview?league=Ancestor&type=UniqueWeapon"

response = requests.get(url)
data = response.json()

# 아이템 데이터 정리
items = data['lines']

# 상위 10개 아이템만 보기 좋게 출력
df = pd.DataFrame(items)
df[['name', 'chaosValue', 'icon']].head(10)

# HTML 테이블로 보기 좋게 만들기
html_table = "<table border='1' style='border-collapse: collapse; text-align: center;'>"
html_table += "<tr><th>아이템 이름</th><th>카오스 가격</th><th>아이콘</th></tr>"

for index, row in df.head(10).iterrows():
    html_table += f"<tr>"
    html_table += f"<td>{row['name']}</td>"
    html_table += f"<td>{round(row['chaosValue'], 2)}</td>"
    html_table += f"<td><img src='{row['icon']}' width='40'></td>"
    html_table += f"</tr>"

html_table += "</table>"

# 결과 출력
print(html_table)

import requests

# --- 여기에 너의 봇 토큰과 채팅 ID 넣기 ---
BOT_TOKEN = '8038373130:AAEwhUIQu5fxmqMP-nBx-dNes00GA6hWlnQ'
CHAT_ID = '7595444442'

# --- 메세지 전송 함수 ---
def send_telegram_message(html):
    send_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        'chat_id': CHAT_ID,
        'text': html,
        'parse_mode': 'HTML',
        'disable_web_page_preview': False
    }
    res = requests.post(send_url, data=payload)
    return res.json()

# --- html_table을 전송! ---
send_telegram_message(html_table)

import requests

# --- 여기에 너의 봇 토큰과 채팅 ID 넣기 ---
BOT_TOKEN = '8038373130:AAEwhUIQu5fxmqMP-nBx-dNes00GA6hWlnQ'
CHAT_ID = '7595444442'

# --- 메세지 전송 함수 ---
def send_telegram_message(html):
    send_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        'chat_id': CHAT_ID,
        'text': html,
        'parse_mode': 'HTML',
        'disable_web_page_preview': False
    }
    res = requests.post(send_url, data=payload)
    return res.json()

# --- html_table을 전송! ---
send_telegram_message(html_table)

html_table = "<table border='1' style='border-collapse: collapse; text-align: center;'>"
html_table += "<tr><th>아이템 이름</th><th>카오스 가격</th><th>아이콘</th></tr>"

for index, row in df.head(10).iterrows():
    html_table += f"<tr>"
    html_table += f"<td>{row['name']}</td>"
    html_table += f"<td>{round(row['chaosValue'], 2)}</td>"
    html_table += f"<td><img src='{row['icon']}' width='40'></td>"
    html_table += f"</tr>"

html_table += "</table>"

import requests
import pandas as pd

# poe2.ninja API에서 인기 아이템 데이터 가져오기
url = "https://poe.ninja/api/data/itemoverview?league=Ancestor&type=UniqueWeapon"
response = requests.get(url)
data = response.json()

# 데이터프레임으로 변환
items = data['lines']
df = pd.DataFrame(items)

html_table = "<table border='1' style='border-collapse: collapse; text-align: center;'>"
html_table += "<tr><th>아이템 이름</th><th>카오스 가격</th><th>아이콘</th></tr>"

for index, row in df.head(10).iterrows():
    html_table += f"<tr>"
    html_table += f"<td>{row['name']}</td>"
    html_table += f"<td>{round(row['chaosValue'], 2)}</td>"
    html_table += f"<td><img src='{row['icon']}' width='40'></td>"
    html_table += f"</tr>"

html_table += "</table>"

send_telegram_message(html_table)

import requests

# --- 여기에 너의 봇 토큰과 채팅 ID 넣기 ---
BOT_TOKEN = '8038373130:AAEwhUIQu5fxmqMP-nBx-dNes00GA6hWlnQ'
CHAT_ID = '7595444442'

# --- 메세지 전송 함수 ---
def send_telegram_message(html):
    send_url = f"https://api.telegram.org/bot{BOT_TOKEN}/sendMessage"
    payload = {
        'chat_id': CHAT_ID,
        'text': html,
        'parse_mode': 'HTML',
        'disable_web_page_preview': False
    }
    res = requests.post(send_url, data=payload)
    return res.json()

# --- html_table을 전송! ---
send_telegram_message(html_table)

# 텍스트로 요약해서 보내기
message = "🔥 오늘의 인기 유니크 무기 Top 5 🔥\n\n"

for index, row in df.head(5).iterrows():
    message += f"{index+1}. {row['name']} - {round(row['chaosValue'], 2)} chaos\n"

send_telegram_message(message)

